import { Link } from 'react-router-dom';
import { MapPin, Plus, User } from 'lucide-react';
import { SearchBar } from './SearchBar';

interface HeaderProps {
  onOpenUpload: () => void;
  onSearch: (query: string) => Promise<void>;
  searchLoading: boolean;
}

export const Header = ({ onOpenUpload, onSearch, searchLoading }: HeaderProps) => {
  return (
    <header className="mb-8 space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <p className="text-sm text-ai-200">AI-powered memory intelligence</p>
          <h1 className="text-3xl font-bold text-white">Memories AI</h1>
        </div>
        <div className="flex gap-2">
          <Link to="/profile" className="rounded-xl border border-white/15 bg-slate-800/70 px-4 py-2 text-white">
            <User className="mr-2 inline h-4 w-4" />Profile
          </Link>
          <Link to="/map" className="rounded-xl border border-white/15 bg-slate-800/70 px-4 py-2 text-white">
            <MapPin className="mr-2 inline h-4 w-4" />Map
          </Link>
          <button onClick={onOpenUpload} className="rounded-xl bg-ai-500 px-4 py-2 font-medium text-white hover:bg-ai-700">
            <Plus className="mr-2 inline h-4 w-4" />New Memory
          </button>
        </div>
      </div>
      <SearchBar onSearch={onSearch} loading={searchLoading} />
      <p className="text-xs text-slate-400">Results are generated by vector similarity, not exact keyword matching.</p>
    </header>
  );
};
