import { useEffect } from 'react';
import { Brain, Calendar, MapPin, Sparkles } from 'lucide-react';
import { useParams } from 'react-router-dom';
import { MemoryCard } from '../components/memory/MemoryCard';
import { useMemoryStore } from '../store/memoryStore';
import { formatReadableDate } from '../utils/date';

export const MemoryDetailPage = () => {
  const { id = '' } = useParams();
  const { selectedMemory, relatedMemories, loading, getMemoryDetail, loadRelated } = useMemoryStore();

  useEffect(() => {
    if (!id) return;
    void getMemoryDetail(id);
    void loadRelated(id);
  }, [id, getMemoryDetail, loadRelated]);

  if (loading || !selectedMemory) {
    return <div className="min-h-screen bg-slate-950 p-8 text-blue-100">Loading memory...</div>;
  }

  return (
    <div className="min-h-screen bg-slate-950 pb-12 text-white">
      <section className="relative h-[52vh] min-h-[320px] overflow-hidden">
        <img src={selectedMemory.image} alt={selectedMemory.title} className="h-full w-full object-cover" />
        <div className="absolute inset-0 bg-slate-950/45 backdrop-blur-sm" />
        <div className="absolute inset-0 flex items-end p-8">
          <div>
            <h1 className="text-4xl font-bold">{selectedMemory.title}</h1>
            <div className="mt-3 flex flex-wrap gap-2 text-sm text-blue-100">
              <span className="rounded-full bg-black/40 px-3 py-1"><Calendar className="mr-1 inline h-4 w-4" />{formatReadableDate(selectedMemory.date)}</span>
              <span className="rounded-full bg-black/40 px-3 py-1"><MapPin className="mr-1 inline h-4 w-4" />{selectedMemory.location}</span>
              <span className="rounded-full bg-black/40 px-3 py-1"><Brain className="mr-1 inline h-4 w-4" />AI emotion: {selectedMemory.emotion}</span>
            </div>
          </div>
        </div>
      </section>

      <div className="mx-auto mt-8 max-w-6xl space-y-8 px-4">
        <section className="rounded-xl border border-blue-400/30 bg-slate-900/70 p-6">
          <h2 className="mb-2 text-xl font-semibold">AI-generated description</h2>
          <p className="text-blue-100/90">{selectedMemory.description}</p>
          <p className="mt-2 inline-flex items-center gap-1 text-xs text-blue-300"><Sparkles className="h-3.5 w-3.5" /> Generated by image captioning + emotional analysis model.</p>
        </section>

        <section>
          <h3 className="mb-3 text-2xl font-semibold text-blue-100">Related Memories</h3>
          <p className="mb-4 text-sm text-blue-300">Retrieved through embedding similarity search.</p>
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
            {relatedMemories.map((memory) => (
              <MemoryCard key={memory.id} memory={memory} />
            ))}
          </div>
        </section>
      </div>
    </div>
  );
};
